### ISSUE TITLE
יש בעיה בנראות כפתור ההורדה

### ISSUE THREAD

**Issue by rhhfk** [chaim-chv/files-sending-for-netfree-users#1]
כפי שכבר דווחתי במתמחים טופ, כפתור הורדה לא נראה באמת כמו שצלמת לנו אותו, נשמח שתשפר זאת
@מתחיל מומחה

**Comment by chaim-chv** [comment]
טוב..
לא היה לי כוח להתחיל להתסבך, פשוט שיניתי את הטקסט של הכפתור ל"הורדה" וזהו..
תיכנס אצלך לתפריט של התוסף ותלחץ על הסמל של עדכון, זה יתעדכן
מקווה שזה פותר לך את הבעיה
בהצלחה!

**Comment by rhhfk** [comment]
תודה, מתוק!
ובשבילך - thanks sweetie!
